version: '3.8'

services:
  fider:
    image: getfider/fider:stable
    container_name: buyermap-feedback
    environment:
      # Database Configuration
      - FIDER_DB_TYPE=sqlite
      - FIDER_DB_CONNECTION=/data/fider.db
      
      # Server Configuration
      - FIDER_HTTP_PORT=3001
      - FIDER_SITE_URL=http://localhost:3001
      
      # SMTP Configuration (development - can be updated later)
      - FIDER_SMTP_HOST=smtp.gmail.com
      - FIDER_SMTP_PORT=587
      - FIDER_SMTP_USERNAME=${FIDER_SMTP_USERNAME:-your-email@gmail.com}
      - FIDER_SMTP_PASSWORD=${FIDER_SMTP_PASSWORD:-your-app-password}
      - FIDER_SMTP_FROM=${FIDER_SMTP_FROM:-feedback@buyermap.com}
      
      # Security
      - FIDER_JWT_SECRET=${FIDER_JWT_SECRET:-change-this-in-production}
      
      # Optional: Basic branding
      - FIDER_TITLE=BuyerMap Feedback
      - FIDER_DESCRIPTION=Share your ideas and feedback for BuyerMap
      
    ports:
      - "3001:3001"
    volumes:
      - fider_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: buyermap-proxy
    profiles: ["production"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - fider
    restart: unless-stopped

volumes:
  fider_data:
    driver: local

networks:
  default:
    name: buyermap-network 